### ISSUE TITLE
Memory limit

### ISSUE THREAD

**Issue by balsama** [drupal-speedrun/speedrun#3]
Had to bump the memory limit to 512 to get install to work after the addition of the content migration.

Not a problem in itself - but we need to remember how intensive it is when we try to do this on other servers and in other environments.

**Comment by phenaproxima** [comment]
Yeah, the migration would be a lot smoother in this regard, but because it's such a bitch to get Migrate working right now (there are two core issues that need to be sorted out to make it smoother, I have one nearly to RTBC and the other is delayed on that one), I think this is probably our best bet at the moment. =\

**Comment by balsama** [comment]
Understandable. Thanks.
